ABCI:
  resource_type: rt_F=1

generic:
  workspace: "./work"
  job_command: "python user.py"

resource:
  type: "local"
  num_node: 1

optimize:
  search_algorithm: "optimizer.MyOptimizer"
  goal: "minimize"
  trial_number: 15
  rand_seed: 42
  parameters:
    - name: "lr"
      type: "uniform_float"
      lower: 1.0e-4
      upper: 1.0
    -
      name: "weight_lr_ratios"
      type: "uniform_float"
      lower: 1.0e-6
      upper: 1.0e-3
    - name: "batch_size"
      type: "uniform_int"
      lower: 64
      upper: 256
    - name: "momentum"
      type: "uniform_float"
      lower: 0.8
      upper: 1.0

job_setting:
  cancel_retry: 3
  cancel_timeout: 60
  expire_retry: 3
  expire_timeout: 60
  finished_retry: 3
  finished_timeout: 60
  job_loop_duration: 0.5
  job_retry: 2
  job_timeout: 60
  kill_retry: 3
  kill_timeout: 60
  result_retry: 1
  runner_retry: 3
  runner_timeout: 60
  running_retry: 3
  running_timeout: 60
  init_fail_count: 100
  name_length: 6
  random_scheduling: false
  #random_scheduling: true

sleep_time:
  master: 1
  scheduler: 1
  optimizer: 1

logger:
  file:
    master: "master.log"
    optimizer: "optimizer.log"
    scheduler: "scheduler.log"
  log_level:
    #master: "DEBUG"
    master: "CRITICAL"
    #optimizer: "DEBUG"
    optimizer: "CRITICAL"
    #scheduler: "DEBUG"
    scheduler: "CRITICAL"
  stream_level:
    master: "CRITICAL"
    optimizer: "CRITICAL"
    scheduler: "CRITICAL"

verification:
  is_verified: false
  condition: []
